// Generated by Selenium IDE

import io.github.bonigarcia.seljup.SeleniumJupiter;
import org.checkerframework.checker.units.qual.C;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.How;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

@ExtendWith(SeleniumJupiter.class)
public class Ex2Refactor {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp(FirefoxDriver driver) {
    this.driver = driver;
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void webtesting() {

    HomePage home = new HomePage(driver);

    assertThat(home.getTitle(), is("Welcome to the Simple Travel Agency!"));

    home.selectDepartureCity();
    home.selectDestinationCity();
    home.findFlights();

    ListOfFlightsPage flightsPage = new ListOfFlightsPage(driver);

    assertThat(flightsPage.getHomeText(), is("home"));

    flightsPage.chooseFlight();

    CustumerInfo custumerInfo = new CustumerInfo(driver);

    assert(custumerInfo.getNumberOfButtons() > 0);

    custumerInfo.insertName();
    custumerInfo.insertAddress();
    custumerInfo.insertCity();
    custumerInfo.insertState();
    custumerInfo.insertZipCode();
    custumerInfo.insertCreditCardNumber();
    custumerInfo.insertNameOnCard();
    custumerInfo.confirm();

    ConfirmationPage confirmationPage = new ConfirmationPage(driver);

    assertThat(confirmationPage.getTitle(), is("Thank you for your purchase today!"));
    assertThat(confirmationPage.getZipCode(), is("888888"));
    assert(confirmationPage.getNumberOfButtons() > 0);
  }
}
